# Generated by Django 2.2.23 on 2021-06-02 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review_post',
            old_name='user',
            new_name='poster',
        ),
    ]
