# Generated by Django 2.2.23 on 2021-05-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Enter full name', max_length=100)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=25)),
                ('birthdate', models.DateField()),
            ],
        ),
    ]
