# Generated by Django 2.2.23 on 2021-06-07 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
